mysite/blog/urls.py
from django.conf.urls import url, include

from blog import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^details/(?P<article_id>\d+)$', views.article_page,name='article_page'),
    url(r'^edit/(?P<article_id>\d+)$', views.edit_page,name='edit_page'),
    url(r'^add$', views.add),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),
]

mysite/blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from . import models


def index(request):
    # 写法一
    # oneArticle = models.Article.objects.get(pk = 1)
    # 写法二
    Article = models.Article.objects.all()
    return render(request, 'blog/index.html', {"articles": Article})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')

    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def add(request):
    id = request.POST.get('id')
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')

    # 修改
    if id:
        article = models.Article.objects.get(pk=id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article': article})
    else:
        models.Article.objects.create(title=title, content=content)

        return HttpResponseRedirect('/blog/index')  # 跳转首页

        # return HttpResponse(content) # 调试

mysite/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br>
<h3>{{article.content}}</h3>
<br><br>
<a href="/blog/edit/{{article.id}}">修改文章</a>
</body>
</html>

mysite/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit_page</title>
</head>
<body>
<form action="/blog/add" method="post">
    {% csrf_token %}

    <input type="hidden" name="id" value="{{article.id}}">
    <label >
        标题<input type="text" name="title" value="{{article.title}}" >
    </label>
    <br>
    <label >
        文章内容<input type="text" name="content"  value="{{article.content}}">
    </label>
    <br>

    <input type="submit" value="提交">

</form>
</body>
</html>

mysite/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
<ul>
{% for article in articles %}
    <li><a href="/blog/details/{{article.id}}">{{article.title}}</a></li>
{% endfor %}
</ul>
</body>
</html>